#! /bin/sh

sxhkd &

bspc config border_width        2
bspc config window_gap          5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc rule -a chromium desktop=^1
bspc rule -a nvim-qt desktop=^2
autostart &
panel &
